import = [
    "~/.config/alacritty/themes/themes/monokai_charcoal.toml"
]

[window]
decorations = "None"
padding.x = 10
padding.y = 10
option_as_alt = "Both"
startup_mode = "Maximized"

opacity = 0.95

[font]
normal.family = "JetBrainsMono Nerd Font Mono"
size = 24

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "zellij -l welcome"]

[keyboard]
bindings = [
    { key = "Right", mods = "Alt", chars = "\u001BF" },
    { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
